### PR TITLE
NativeDate: refactor to use java.time, fix locales argument

### PR DESCRIPTION
**Pull request by duonglaiquang**
### This PR does the following
- Improve `NativeDate` by
~~- Add `Japan Standard Time (JST)` support~~
  - Change to use `DateTimeFormatter` instead of `SimpleDateFormat`
  - Fix [Date.prototype.toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) currently not handling locales argument
  - Make the formatter use `Context.timezone` instead of system default
  - Use `FormatStyle.SHORT` for the formatter to make it behave more like real browsers when `Intl.DateTimeFormat` is not supported.

### CODE REVIEW

**Comment by rbri** [comment]
@duonglaiquang have started working on this but

console.log(new Date('Sat, 18 Dec 2021 22:23:00 JST').toISOString()) gives me an error.
You are sure real browsers are supporting JST - and if yes do you have an example?

**Comment by duonglaiquang** [comment]
@rbri Thanks for the head up and sorry i should have done some more testing with real browsers.
I also added 1 more commit, could you check it.

**Comment by rbri** [comment]
@duonglaiquang sorry for the long delay to get this done. But for private reasons i had not that much time during the last months and the refactoring done at the rhino side was also huge.

Hopefully now everything is in place and we have a bunch more tests for this.

Thanks for this contribution...

**Comment by rbri** [comment]
@duonglaiquang made a new snapshot build...

**Pull request closed without merging**
